// auto-generated by album-webdav-config plugin
import type { AlbumWebDavFrontmatterConfig } from '../types/album'

export const albumWebDavPublicConfig: Record<string, AlbumWebDavFrontmatterConfig> = {
  'web-jiami': {"url":"https://ogi.teracloud.jp/dav/","username":"username"},
  'web-kaif': {"url":"https://ogi.teracloud.jp/dav/","username":"username"},
}

export function getAlbumWebDavPublicConfig(slug: string) {
  return albumWebDavPublicConfig[slug]
}
