/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/anime/': RouteRecordInfo<
      '/anime/',
      '/anime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comment/': RouteRecordInfo<
      '/comment/',
      '/comment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/': RouteRecordInfo<
      '/gallery/',
      '/gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/bizhi/': RouteRecordInfo<
      '/gallery/bizhi/',
      '/gallery/bizhi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/jiamio/': RouteRecordInfo<
      '/gallery/jiamio/',
      '/gallery/jiamio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/README': RouteRecordInfo<
      '/gallery/README',
      '/gallery/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/web-jiami/': RouteRecordInfo<
      '/gallery/web-jiami/',
      '/gallery/web-jiami',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/web-kaif/': RouteRecordInfo<
      '/gallery/web-kaif/',
      '/gallery/web-kaif',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navigation/': RouteRecordInfo<
      '/navigation/',
      '/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/hello-pyro': RouteRecordInfo<
      '/posts/hello-pyro',
      '/posts/hello-pyro',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-world': RouteRecordInfo<
      '/posts/hello-world',
      '/posts/hello-world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-1': RouteRecordInfo<
      '/posts/valaxy-1',
      '/posts/valaxy-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-10': RouteRecordInfo<
      '/posts/valaxy-10',
      '/posts/valaxy-10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-2': RouteRecordInfo<
      '/posts/valaxy-2',
      '/posts/valaxy-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-3': RouteRecordInfo<
      '/posts/valaxy-3',
      '/posts/valaxy-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-4': RouteRecordInfo<
      '/posts/valaxy-4',
      '/posts/valaxy-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-5': RouteRecordInfo<
      '/posts/valaxy-5',
      '/posts/valaxy-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-6': RouteRecordInfo<
      '/posts/valaxy-6',
      '/posts/valaxy-6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-7': RouteRecordInfo<
      '/posts/valaxy-7',
      '/posts/valaxy-7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-8': RouteRecordInfo<
      '/posts/valaxy-8',
      '/posts/valaxy-8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-9': RouteRecordInfo<
      '/posts/valaxy-9',
      '/posts/valaxy-9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__26c2e4e40056577f3391180093fd2e8a/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.10_@babel+parse_de6c62875951dae520b9ba415ab31be1/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/anime/index.md': {
      routes:
        | '/anime/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/comment/index.md': {
      routes:
        | '/comment/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/index.md': {
      routes:
        | '/gallery/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/bizhi/index.md': {
      routes:
        | '/gallery/bizhi/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/jiamio/index.md': {
      routes:
        | '/gallery/jiamio/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/README.md': {
      routes:
        | '/gallery/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/web-jiami/index.md': {
      routes:
        | '/gallery/web-jiami/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/web-kaif/index.md': {
      routes:
        | '/gallery/web-kaif/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/navigation/index.md': {
      routes:
        | '/navigation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/posts/hello-pyro.md': {
      routes:
        | '/posts/hello-pyro'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello-world.md': {
      routes:
        | '/posts/hello-world'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-1.md': {
      routes:
        | '/posts/valaxy-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-10.md': {
      routes:
        | '/posts/valaxy-10'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-2.md': {
      routes:
        | '/posts/valaxy-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-3.md': {
      routes:
        | '/posts/valaxy-3'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-4.md': {
      routes:
        | '/posts/valaxy-4'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-5.md': {
      routes:
        | '/posts/valaxy-5'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-6.md': {
      routes:
        | '/posts/valaxy-6'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-7.md': {
      routes:
        | '/posts/valaxy-7'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-8.md': {
      routes:
        | '/posts/valaxy-8'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/valaxy-9.md': {
      routes:
        | '/posts/valaxy-9'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/search/index.md': {
      routes:
        | '/search/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
